### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/daylight-awesome#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by githubteacher** [comment]
⚡️ :octocat:

**Comment by nagjamna** [comment]
:+1:

**Comment by rajeshmasuti** [comment]
:new: :construction_worker_man:

**Comment by rlcscde** [comment]
:octocat: gitbhub training

**Comment by brianmonthie** [comment]
Commenting here.  :soccer:

**Comment by ServatDjoo** [comment]
:1st_place_medal: Nice Training

**Comment by dmudigonda** [comment]
:+1:

**Comment by saikat2k12** [comment]
:+1:

**Comment by tanusreepaul** [comment]
:+1: myfirstgithubtraining

**Comment by muraliveeramallu** [comment]
:+1:

**Comment by partha-git** [comment]
:100:

**Comment by srinivas-malyala** [comment]
Hello World

**Comment by mithunganguly** [comment]
Hiccup resolved...Able to post comment :)

**Comment by githubteacher** [comment]
@githubteacher Hello!

**Comment by vtiwari27** [comment]
Hello!
